test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,6 +29,15 @@ jobs:
       - uses: actions/checkout@v3
         with:
           submodules: true
+      - name: Check .sqlx directory presence
+        run: |
+          if [ ! -d ".sqlx" ]; then
+            echo ".sqlx directory is missing. Failing the workflow."
+            exit 1
+          else
+            echo ".sqlx directory is present. Continuing..."
+            ls -la .sqlx
+          fi
       - name: Checkout submodules
         run: git submodule update --init --recursive
       - uses: actions/setup-go@v4
