test CI updates

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,8 +2,8 @@
 on:
   push:
     branches: [main]
-  pull_request_review:
-    types: [submitted]
+  pull_request:
+    branches: [main]
 
 name: CI
 
@@ -21,30 +21,27 @@ jobs:
 
   check:
     name: Check
-    if: github.event.review.state == 'approved'
-    strategy:
-      matrix:
-        include:
-          - os: ubuntu-latest
-            toolchain: stable-x86_64-unknown-linux-gnu
-          - os: macos-latest
-            toolchain: stable-x86_64-apple-darwin
-    runs-on: ${{ matrix.os }}
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
           submodules: true
       - name: Checkout submodules
         run: git submodule update --init --recursive
-      - uses: actions/setup-go@v4 # we need go to build go-waku
+      - uses: actions/setup-go@v4
         with:
           go-version: '1.19'
       - uses: actions-rs/toolchain@v1
         with:
           profile: minimal
-          toolchain: ${{ matrix.toolchain }}
+          toolchain: stable-x86_64-unknown-linux-gnu
           default: true
           override: true
+      - name: List project directory contents after checkout
+        run: |
+          ls -la
+          echo "Contents of .sqlx directory (if present):"
+          ls -la .sqlx || echo ".sqlx directory not found."
       - uses: actions-rs/cargo@v1
         continue-on-error: false
         with:
@@ -56,28 +53,20 @@ jobs:
 
   test:
     name: Test Suite
-    if: github.event.review.state == 'approved'
-    strategy:
-      matrix:
-        include:
-          - os: ubuntu-latest
-            toolchain: stable-x86_64-unknown-linux-gnu
-          - os: macos-latest
-            toolchain: stable-x86_64-apple-darwin
-    runs-on: ${{ matrix.os }}
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
           submodules: true
       - name: Checkout submodules
         run: git submodule update --init --recursive
-      - uses: actions/setup-go@v4 # we need go to build go-waku
+      - uses: actions/setup-go@v4
         with:
           go-version: '1.19'
       - uses: actions-rs/toolchain@v1
         with:
           profile: minimal
-          toolchain: ${{ matrix.toolchain }}
+          toolchain: stable-x86_64-unknown-linux-gnu
           default: true
           override: true
       - uses: actions-rs/cargo@v1
