quickly test ci script on dev

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,9 +1,10 @@
-# copy of https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
 on:
   push:
-    branches: [main]
-  pull_request_review:
-    types: [submitted]
+    branches:
+      - '**'
+  pull_request:
+    branches:
+      - '**'
 
 name: CI
 
@@ -21,30 +22,38 @@ jobs:
 
   check:
     name: Check
-    if: github.event.review.state == 'approved'
-    strategy:
-      matrix:
-        include:
-          - os: ubuntu-latest
-            toolchain: stable-x86_64-unknown-linux-gnu
-          - os: macos-latest
-            toolchain: stable-x86_64-apple-darwin
-    runs-on: ${{ matrix.os }}
+    env:
+      SQLX_OFFLINE: true
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
           submodules: true
+      - name: Check .sqlx directory presence
+        run: |
+          if [ ! -d ".sqlx" ]; then
+            echo ".sqlx directory is missing. Failing the workflow."
+            exit 1
+          else
+            echo ".sqlx directory is present. Continuing..."
+            ls -la .sqlx
+          fi
       - name: Checkout submodules
         run: git submodule update --init --recursive
-      - uses: actions/setup-go@v4 # we need go to build go-waku
+      - uses: actions/setup-go@v4
         with:
           go-version: '1.19'
       - uses: actions-rs/toolchain@v1
         with:
           profile: minimal
-          toolchain: ${{ matrix.toolchain }}
+          toolchain: stable-x86_64-unknown-linux-gnu
           default: true
           override: true
+      - name: List project directory contents after checkout
+        run: |
+          ls -la
+          echo "Contents of .sqlx directory (if present):"
+          ls -la .sqlx || echo ".sqlx directory not found."
       - uses: actions-rs/cargo@v1
         continue-on-error: false
         with:
@@ -56,28 +65,20 @@ jobs:
 
   test:
     name: Test Suite
-    if: github.event.review.state == 'approved'
-    strategy:
-      matrix:
-        include:
-          - os: ubuntu-latest
-            toolchain: stable-x86_64-unknown-linux-gnu
-          - os: macos-latest
-            toolchain: stable-x86_64-apple-darwin
-    runs-on: ${{ matrix.os }}
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
           submodules: true
       - name: Checkout submodules
         run: git submodule update --init --recursive
-      - uses: actions/setup-go@v4 # we need go to build go-waku
+      - uses: actions/setup-go@v4
         with:
           go-version: '1.19'
       - uses: actions-rs/toolchain@v1
         with:
           profile: minimal
-          toolchain: ${{ matrix.toolchain }}
+          toolchain: stable-x86_64-unknown-linux-gnu
           default: true
           override: true
       - uses: actions-rs/cargo@v1
